thephpleague/glide

- composer.json
Flysystem has been tagged.
Perhaps a new tag would be nice? Because the stable version still requires 0.5
> Remove dev constraint

- src/Server.php
- tests/ServerTest.php
Simply wrapping the `$path` returned in `getSourcePath()` with `urldecode()` appears to fix #32.
> Decode URL entities in path

- src/Server.php
- tests/ServerTest.php
These changes address the concurrent cache write issue revealed by https://github.com/thephpleague/glide/issues/38.
> Add graceful handling of cache write failure due to already existent cache file caused by race condition.

- .travis.yml
- composer.json
* Use `composer update` to test against the highest dependencies
* Also test against the lowest supported dependencies
* Added testing on the upcoming php release (7.0)
* Use [container-based](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) travis builds 
Doing this uncovered an [issue](https://travis-ci.org/duncan3dc/glide/builds/52405993) in the dependencies. This looks like a problem in `intervention/image`, where they are misstating their lowest supported dependencies. Bumping glide's supported version to `~2.1` fixes that but I'm not sure whether you'd rather pursue a fix with intervention instead.
> A bunch of stuff for Travis CI

- src/Api/Manipulator/Size.php
- tests/Api/Manipulator/SizeTest.php
When one of the dimensions requested is the same as the original the image is not resized.
> Image is not resized

- .gitignore
- src/Server.php
- src/ServerFactory.php
WIP. As per Jonathan's request, this potential fix for Glide's current inability to disable caching is being submitted as a pull request without unit test updates for the sake of implementation review.
These modifications enable the passing of boolean false as the value for the ‘cache’ parameter to the server factory. Doing so bypasses the cache writing process and serves the image from source.
> Add the ability to disable caching by passing false as the cache parameter

- .gitignore
This should never have been added. It belongs in your system .gitignore file.
> Remove .DS_STORE from .gitignore

- src/Manipulators/Size.php
- tests/Manipulators/SizeTest.php
When resizing an image which is smaller than the dimensions you want to
resize it to in one or both directions, the fit=fill option allows you
to specify a fill color (when combined with the Background manipulator)
to fill the extra canvas space.
This is accomplished using a query like `?w=300&fit=fill&bg=000` to resize
the image to 300 pixels wide while filling any new canvas space with
black.
> Add fit=fill feature for resize

- README.md
A possessive belonging to an "it" doesn't need an apostrophe. Don't believe me? Ask [the Oatmeal](http://theoatmeal.com/comics/apostrophe) (look for the velociraptor)!
> remove Bad Apostrophe from README.md

- src/Server.php
This commit fixes possible `rewind(): stream does not support seeking` errors.
> Make sure stream is seekable before using `rewind()`

- src/Server.php
- src/ServerFactory.php
- tests/ServerFactoryTest.php
- tests/ServerTest.php
Hey there.
I'd like to be able to add file extensions to the cached images so they can be served directly.
In our app (Statamic, in this case), we'll have an option to pre-generate the images and use this approach. Obviously we'd lose the dynamic URL based nature of Glide, but this would be a switch people could flick to increase performance.
On heavier sites, loading an image directly is considerably faster than bootstrapping the app.
> Add support for caching with file extensions

- docs/1.0/config/integrations/laravel.md
The `SymfonyResponseFactory` can be constructed with an instance of the `Symfony\Component\HttpFoundation\Request`.
This will set the `last-modified` header based on the timestamp of the cached image.
Perhaps this should be added to the Symfony integration page as well, but I'm not sure how to pass in the Request object.
> Documentation: Add Request object to LaravelResponseFactory

- src/Server.php
- tests/ServerTest.php
I ran into a bug where if a path started with the baseUrl, it would get trimmed off incorrectly.
For example: if your `baseUrl` is `img`, and you do `$server->getSourcePath('imgur.jpg')` or `'img-0001.jpg` or something, it would return `ur.jpg` and `-0001` respectively.
I believe this PR fixes it by making sure there's a slash in the substring.
> Fix source being trimmed when it begins with the baseUrl

- docs/1.0/config/integrations/zend.md
Documentation for the Zend Diactoros Response Factory references an incorrect composer package name.
> Fix typo in documentation.

- src/Server.php
- tests/ServerTest.php
When you enable `setCacheWithFileExtensions` and use `fm=pjpg`, the file was being saved as `.pjpg`. Now it'll use `jpg`.
I'm not sure if this is the best way to fix it.
> Save pjpg as jpg when including file extensions

- docs/1.0/api/crop.md
- src/Manipulators/Size.php
- tests/Manipulators/SizeTest.php
This PR adds support for an optional third float value to be passed to `crop-` which will zoom in the image.
It works the same way that Imgix's [focal point zoom](https://docs.imgix.com/apis/url/focalpoint-crop/fp-z) does on its version of [their focal point crop feature](https://docs.imgix.com/apis/url/focalpoint-crop).
It *does* upscale if you choose to zoom far enough, but it's consistent with how Imgix behaves.
Leaving off the number will default to 1, a zoom level of 100%, which means it works like it did before.
(May also be a solution to #234?)
Everything is focused on `29-81` (the yellow kayak's tag)
**Squares** at zoom levels of 1 (current/default behavior), 2, 5, and 10.
**Landscapes**
**Portraits**
> Add a zoom option to focal crop

- .travis.yml
- composer.json
- src/Server.php
If an exception occurs during this try/catch (eg. invalid file type, file too large etc), the /tmp/GlideXXX files will not be deleted. This will fill the /tmp folder and can lead to problems when it's not deleted regularly.
Should fix https://github.com/thephpleague/glide/issues/192
> Always delete tmp file

- docs/1.0/config/advanced-usage.md
- docs/1.0/config/setup.md
- src/Server.php
- src/ServerFactory.php
- tests/ServerFactoryTest.php
- tests/ServerTest.php
Introduce the ability to configure the temporary directory used to store EXIF data. It's an adaptation of @jaapio work in https://github.com/thephpleague/glide/pull/165, thanks for the PR!
Replace https://github.com/thephpleague/glide/pull/165
Fixes https://github.com/thephpleague/glide/issues/156
Fixes https://github.com/thephpleague/glide/issues/186
> Allow to configure temp directory

- composer.json
- docs/1.0/config/advanced-usage.md
- docs/1.0/config/responses.md
- src/Manipulators/Watermark.php
- src/Responses/PsrResponseFactory.php
- src/Responses/ResponseFactoryInterface.php
- src/Server.php
- src/ServerFactory.php
- tests/Manipulators/WatermarkTest.php
- tests/Responses/PsrResponseFactoryTest.php
- tests/ServerFactoryTest.php
- tests/ServerTest.php
This PR contains changes that remove Flysystem 1 and adapt to Flysystem 2.
Most of the work went into changing test suite to mimic Flysystem 2 exception logic, while changes to the code are rather simple.
I create another PR to visualize changes needed to migrate fully from V1 to V2 in case this will be the way chosen by maintainers.
> Use only Flysystem v2

- src/Manipulators/Size.php
- tests/Manipulators/SizeTest.php
If I have an image with a size of 1024x553 pixel and I run
```php
(new \League\Glide\Manipulators\Size)
->setParams(['w' => 411, 'fit' => 'max'])
->run($image);
```
on it. I will get an image with the dimensions 409x221 pixel.
It looks like this happens due to the calculations in \League\Glide\Manipulators\Size::resolveMissingDimensions(). For the example above it will keep the width of 411 px and calculate a height of 221 px. Intervention Image rounds numbers differently, resulting in this wrong image size when the image is actually resized to the precalculated size.
To fix this issue I would suggest to rely on the resizing logic of Intervention Image.
> Fix rounding issue with Manipulators\Size

- .github/workflows/test.yaml
- src/Manipulators/Encode.php
- tests/Manipulators/EncodeTest.php
Further to #344, here's a PR to enable TIFF image format support. I saw that there were some vestiges of TIFF format support already (for example the `tif` property in the test case), so I've made use of that. The test suite runs only with the `gd` driver, so operations that require `imagick` (which includes the TIFF format) can't be tested, so I wrote a new test method that reconfigures the test to run with imagick, and skips the test if it's not installed.
I don't understand how the mock works in `testGetFormat` – I tried copying it but couldn't make it work, so I've not created a similar test for that.
> Enable TIFF image format handling, fixes #344

- .github/workflows/test.yaml
- src/Manipulators/Brightness.php
- src/Manipulators/Contrast.php
- src/Manipulators/Crop.php
- src/Manipulators/Gamma.php
- src/Manipulators/Size.php
- src/Server.php
- src/ServerFactory.php
For **1.x** same as **2.x** version
- **Fix php8.1 deprecations** https://github.com/thephpleague/glide/commit/652771b3c4230dfb981949dbd5e33afb6bff3d34
@ADmad please tag correctly, last one was [tag/1.7.0](https://github.com/thephpleague/glide/releases/tag/1.7.0)
> [1.x] Fix PHP 8.1 deprecations

- docs/2.0/api/encode.md
The docs state that they quality parameter only applies to `jpg` and `pjpg`, this isn't the case it also applies to `wepb` and `avif`
> Updates the docs regarding quality parameter

- docs/2.0/api/adjustments.md
- docs/2.0/api/background.md
- docs/2.0/api/border.md
- docs/2.0/api/crop.md
- docs/2.0/api/effects.md
- docs/2.0/api/encode.md
- docs/2.0/api/flip.md
- docs/2.0/api/orientation.md
- docs/2.0/api/pixel-density.md
- docs/2.0/api/size.md
- docs/2.0/api/watermarks.md
- docs/2.0/index.md
This is only until 2.0 can be added to the demo app. 
Related to #328
> Revert images in demo to 1.0 API

- src/Manipulators/Encode.php
...so that it's visible from outside. As far as I can see there is no public way to obtain a list of the image formats that glide supports (other than docs), so I've moved it to a static method in the Encode Manipulator, and I use that from its own methods too. It's static so it can be overridden easily if someone wants to add (or remove) a format.
This is just an idea – I found that I wanted to find this out when using glide from spatie/image, as otherwise it has to maintain its own list of supported formats, which isn't very DRY.
> Break out the list of supported image formats

- docs/2.0/api/effects.md
The ["effects" API example documentation](https://github.com/thephpleague/glide/blob/master/docs/2.0/api/effects.md) contains a couple of invalid img src attributes because they don't contain a closing double-quote ("). This PR fixes that!
> Fix: invalid img src attribute values

- docs/1.0/config/setup.md
- src/Server.php
- src/ServerFactory.php
- tests/ServerTest.php
This would allow to customize the cache path fully.
An alternative would be to call the callable at the end of getCachePath with all the calculated parts (sourcePath, md5, groupCacheInFolders, cachePathPrefix, cacheWithFileExtensions, ext).
I also bound this to the Server instance so that we may its method within the callable.
> Custom path callable

- src/Manipulators/Encode.php
@konnng-dev I took your changes from https://github.com/Art4/glide/pull/2 to fix interlacing.
Though when testing the generated image, interlacing doesn't seem to work for JPEGs when using GD.
With Imagick `identify -verbose kayak.jpeg | grep Interlace` gives `Interlace: JPEG` but with GD it gives `Interlace: None`.
It seems to work fine for PNGs for either driver.
@Art4 BTW Glide v2 doesn't interlace PNGs but you have added interlacing for all PNGs in v3. Is that intentional?
> Fix interlacing

- src/Manipulators/Encode.php
Intervention 3 requires quality to be passed as a named argument; see: https://image.intervention.io/v3/basics/image-output#encode-images-by-file-extension
> 3.x-fix-quality

- src/Server.php
It took too long to find a cause of a not working cache setup. The real issue was wrong bucket setup:
```
Unable to write file at location: a. {
"error": {
"code": 400,
"message": "Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access",
"errors": [
{
"message": "Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access",
"domain": "global",
"reason": "invalid"
}
]
}
}.
```
So exceptions should not be hidden as they do help to solve the problem easier.
> Exception message is hidden

- src/Server.php
- tests/ServerTest.php
Since Glide now requires php ^8.1, replace `md5` with `xxh3` for shorter and faster hash, see: https://php.watch/versions/8.1/xxHash
Note this is a breaking change that will trigger all images to be recreated.
Maybe that could be introduced behind an optin flag?
> 3.x-use-xxh3

- src/Api/Api.php
- src/Server.php
- tests/Api/ApiTest.php
- tests/ServerTest.php
- Remove unneeded temp image creation
- Specify only the required binary image decoder class for ImageManager::read()
> Optimize ImageInterface instance creation.

- src/Server.php
Hello,
phpstan v2 complains about catching `FileNotFoundException` when calling the `Server::getImageResponse`.
But `makeImage` can actually throw those errors, so i've added them into the public methods
> add missing throws annotation

- .github/workflows/test.yaml
- src/Api/Api.php
- src/Api/ApiInterface.php
- src/Manipulators/Background.php
- src/Manipulators/BaseManipulator.php
- src/Manipulators/Blur.php
- src/Manipulators/Border.php
- src/Manipulators/Brightness.php
- src/Manipulators/Contrast.php
- src/Manipulators/Crop.php
- src/Manipulators/Filter.php
- src/Manipulators/Flip.php
- src/Manipulators/Gamma.php
- src/Manipulators/ManipulatorInterface.php
- src/Manipulators/Orientation.php
- src/Manipulators/Pixelate.php
- src/Manipulators/Sharpen.php
- src/Manipulators/Size.php
- src/Manipulators/Watermark.php
- src/Server.php
- tests/Api/ApiTest.php
- tests/ServerTest.php
- tests/Signatures/SignatureTest.php
* resolves #412 
- Added new tests to make sure only valid parameters are used
- New interface method for each manipulator to know the API parameters used
- no BC break
> Define API params in order to be able to filter correctly

- composer.json
- src/Api/Encoder.php
- tests/Api/EncoderTest.php
Earlier, if `fm` was not specified then an image with mime-type "image/x-webp" would get encoded as jpg instead of webp, since the mime type is not include in the Encoder::supportedFormats() list.
> Ensure original type is preserved when `fm` is not specified.

- src/Manipulators/BaseManipulator.php
- src/Manipulators/Border.php
- src/Manipulators/Size.php
- src/Manipulators/Watermark.php
- tests/Api/ApiTest.php
Had a typo for an API param 
I wonder if we should throw an exception when a manipulator gets a param that's not allowed?
> Fixed param typo

- docs/3.0/api/crop.md
- docs/3.0/api/size.md
- docs/3.0/api/watermarks.md
- docs/3.0/config/defaults-and-presets.md
- docs/3.0/simple-example.md
- src/Manipulators/Size.php
- tests/Manipulators/SizeTest.php
* resolves #420
Intervention v3 has a `cover` method that works as intended for the `fit=crop` parameter.
https://image.intervention.io/v3/modifying/resizing#cropping--resizing-combined
> Use `cover` method from Intervention

- src/Manipulators/Background.php
- tests/Manipulators/BackgroundTest.php
For the calls of the [Background `bg`](https://glide.thephpleague.com/3.0/api/background/) manipulator Intervention Image has already an own method [`blendTransparency()`](https://image.intervention.io/v3/basics/colors#merge-transparent-areas-with-color) to set the background color of the image. 
This patch simplifies the `Background::class` manipulator in that way and replaces the manual individual steps with the mentioned method.
> Simplify Background::class manipulator

- docs/3.0/config/setup.md
Glide 3 uses Intervention Image 3. This patch adapts the documentation to the 3.x API.
> Fix constructor call of Intervention\Image\ImageManager in docs

- src/Manipulators/Size.php
- tests/Manipulators/SizeTest.php
For the `Size` manipulator operations use a transparent background so that the background color, if specified, is applied by the `Background` manipulator.
> Fix background color not being applied.

- src/Manipulators/Background.php
- tests/Manipulators/BackgroundTest.php
Blending color is used only when outputting to image format which do not support tranparency but the background color when specified should be always used regardless of the output format.
This reverts commit bbf0976365820c50557a541282d6fc15e6325211.
> Revert "Simplify Background::class manipulator"
